# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [15]:
ds=pd.read_csv("Energy_consumption.csv")

In [16]:
ds.head()

,Timestamp,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption
0,2022-01-01 00:00:00,25.139433,43.431581,1565.693999,5,On,Off,2.774699,Monday,No,75.364373
1,2022-01-01 01:00:00,27.731651,54.225919,1411.064918,1,On,On,21.831384,Saturday,No,83.401855
2,2022-01-01 02:00:00,28.704277,58.907658,1755.715009,2,Off,Off,6.764672,Sunday,No,78.270888
3,2022-01-01 03:00:00,20.080469,50.371637,1452.316318,1,Off,On,8.623447,Wednesday,No,56.519850
4,2022-01-01 04:00:00,23.097359,51.401421,1094.130359,9,On,Off,3.071969,Friday,No,70.811732

In [17]:
ds.drop(columns="Timestamp",inplace=True)

In [23]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds["HVACUsage"]=le.fit_transform(ds["HVACUsage"])
ds.head()

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption
0,25.139433,43.431581,1565.693999,5,1,Off,2.774699,Monday,No,75.364373
1,27.731651,54.225919,1411.064918,1,1,On,21.831384,Saturday,No,83.401855
2,28.704277,58.907658,1755.715009,2,0,Off,6.764672,Sunday,No,78.270888
3,20.080469,50.371637,1452.316318,1,0,On,8.623447,Wednesday,No,56.519850
4,23.097359,51.401421,1094.130359,9,1,Off,3.071969,Friday,No,70.811732

In [24]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds["LightingUsage"]=le.fit_transform(ds["LightingUsage"])
ds.head()

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption
0,25.139433,43.431581,1565.693999,5,1,0,2.774699,Monday,No,75.364373
1,27.731651,54.225919,1411.064918,1,1,1,21.831384,Saturday,No,83.401855
2,28.704277,58.907658,1755.715009,2,0,0,6.764672,Sunday,No,78.270888
3,20.080469,50.371637,1452.316318,1,0,1,8.623447,Wednesday,No,56.519850
4,23.097359,51.401421,1094.130359,9,1,0,3.071969,Friday,No,70.811732

In [25]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds["DayOfWeek"]=le.fit_transform(ds["DayOfWeek"])
ds.head()

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption
0,25.139433,43.431581,1565.693999,5,1,0,2.774699,1,No,75.364373
1,27.731651,54.225919,1411.064918,1,1,1,21.831384,2,No,83.401855
2,28.704277,58.907658,1755.715009,2,0,0,6.764672,3,No,78.270888
3,20.080469,50.371637,1452.316318,1,0,1,8.623447,6,No,56.519850
4,23.097359,51.401421,1094.130359,9,1,0,3.071969,0,No,70.811732

In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds["Holiday"]=le.fit_transform(ds["Holiday"])
ds.head()

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption
0,25.139433,43.431581,1565.693999,5,1,0,2.774699,1,0,75.364373
1,27.731651,54.225919,1411.064918,1,1,1,21.831384,2,0,83.401855
2,28.704277,58.907658,1755.715009,2,0,0,6.764672,3,0,78.270888
3,20.080469,50.371637,1452.316318,1,0,1,8.623447,6,0,56.519850
4,23.097359,51.401421,1094.130359,9,1,0,3.071969,0,0,70.811732

In [27]:
x=ds.iloc[:,0:9]
x

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday
0,25.139433,43.431581,1565.693999,5,1,0,2.774699,1,0
1,27.731651,54.225919,1411.064918,1,1,1,21.831384,2,0
2,28.704277,58.907658,1755.715009,2,0,0,6.764672,3,0
3,20.080469,50.371637,1452.316318,1,0,1,8.623447,6,0
4,23.097359,51.401421,1094.130359,9,1,0,3.071969,0,0
...,...,...,...,...,...,...,...,...,...
995,28.619382,48.850160,1080.087000,5,0,0,21.194696,2,0
996,23.836647,47.256435,1705.235156,4,0,1,25.748176,5,1
997,23.005340,48.720501,1320.285281,6,0,1,0.297079,0,1
998,25.138365,31.306459,1309.079719,3,1,0,20.425163,4,1
999,23.051165,42.615421,1018.140606,6,0,1,2.455657,2,0

In [28]:
y=ds["EnergyConsumption"]
y

0      75.364373
1      83.401855
2      78.270888
3      56.519850
4      70.811732
         ...
995    82.306692
996    66.577320
997    72.753471
998    76.950389
999    71.545311
Name: EnergyConsumption, Length: 1000, dtype: float64

In [29]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=1)

In [30]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(xtrain,ytrain)

LinearRegression()

In [31]:
ypred=lr.predict(xtest)

In [32]:
from sklearn.metrics import r2_score
r2_score(ytest,ypred)

0.6228412383479554

In [53]:
from sklearn.tree import DecisionTreeRegressor
ds=DecisionTreeRegressor()
ds.fit(xtrain,ytrain)
ypred=ds.predict(xtest)
print(r2_score(ytest,ypred))

0.11074234666628402